spring.application.name=demand

logging.level.com.example=debug
logging.level.org.springframework.web=debug

# file: `src/main/resources/application.properties`
server.port=8080

logging.level.guru.springframework=debug
spring.flyway.enabled=false

#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=drop-and-create
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-source=metadata
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.drop-target=drop-and-create.sql
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=drop-and-create.sql

spring.jackson.serialization.INDENT_OUTPUT=true
